version: "3.7"

services:
  nginx-proxy-manager:
    restart: unless-stopped
    container_name: nginx-proxy-manager
    image: "jc21/nginx-proxy-manager:latest"
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - /srv/dev-disk-by-uuid-484794a4-ec51-4120-a430-f753ae0a4fd0/docker/docker/proxy/data:/data
      - /srv/dev-disk-by-uuid-484794a4-ec51-4120-a430-f753ae0a4fd0/docker/docker/proxy/letsencrypt:/etc/letsencrypt
