services:
  opengist:
    image: ghcr.io/thomiceli/opengist:1
    container_name: opengist
    restart: unless-stopped
    environment:
      UID: 1000
      GID: 1000
    ports:
      - 6157:6157
      - 2222:2222
    volumes:
      - /home/ad/docker/opengist:/opengist

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/ad/docker/syncthing:/var/syncthing
      - /home/ad/other:/other
    network_mode: host
    restart: unless-stopped

  # syncthing:
  #   image: lscr.io/linuxserver/syncthing:latest
  #   container_name: syncthing
  #   hostname: syncthing #optional
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - /path/to/syncthing/config:/config
  #     - /path/to/data1:/data1
  #     - /path/to/data2:/data2
  #   ports:
  #     - 8384:8384
  #     - 22000:22000/tcp
  #     - 22000:22000/udp
  #     - 21027:21027/udp
  #   restart: unless-stopped