networks:
  forgejo:
    external: false

services:
  forgejo-srv:
    image: codeberg.org/forgejo/forgejo:1.21
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=kkmargo82
    restart: unless-stopped
    networks:
      - forgejo
    volumes:
      - /home/ad/docker/forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3000:3000'
      - '222:22'
    depends_on:
      - db

  forgejo-db:
    image: postgres:14
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=kkmargo82
      - POSTGRES_DB=forgejo
    networks:
      - forgejo
    volumes:
      - /home/ad/docker/postgres:/var/lib/postgresql/data

  opengist:
    image: ghcr.io/thomiceli/opengist:1
    container_name: opengist
    restart: unless-stopped
    environment:
      UID: 1000
      GID: 1000
    ports:
      - 6157:6157
      - 2222:2222
    volumes:
      - /home/ad/docker/opengist:/opengist

  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/ad/docker/syncthing:/var/syncthing
    network_mode: host
    restart: unless-stopped

  # syncthing:
  #   image: lscr.io/linuxserver/syncthing:latest
  #   container_name: syncthing
  #   hostname: syncthing #optional
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Etc/UTC
  #   volumes:
  #     - /path/to/syncthing/config:/config
  #     - /path/to/data1:/data1
  #     - /path/to/data2:/data2
  #   ports:
  #     - 8384:8384
  #     - 22000:22000/tcp
  #     - 22000:22000/udp
  #     - 21027:21027/udp
  #   restart: unless-stopped