version: "2.1"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /srv/dev-disk-by-uuid-484794a4-ec51-4120-a430-f753ae0a4fd0/docker/qbittorrent:/config
      - /srv/dev-disk-by-uuid-218236ca-8e14-47ae-866a-a91e70c88a2a/downloads:/downloads
      - /srv/dev-disk-by-uuid-218236ca-8e14-47ae-866a-a91e70c88a2a/movies:/movies
      - /srv/dev-disk-by-uuid-218236ca-8e14-47ae-866a-a91e70c88a2a/tvshows:/tvshows
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
