services:
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ad/docker/dockge:/app/data
      - /home/ad/docker/dockge/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/home/ad/docker/dockge/stacks
