services:
  plex:
    restart: unless-stopped
    container_name: plex
    image: linuxserver/plex:latest
    network_mode: host
    environment:
      - TZ=America/New_York
      - PLEX_UID=1000
      - PLEX_GID=1000
    volumes:
      - /home/ad/docker/plex:/config
      - /home/ad/media/movies:/movies
      - /home/ad/media/tvshows:/tvshows
      - /home/ad/media/music:/music

  tautulli:
    restart: unless-stopped
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/ad/docker/tautulli:/config
    ports:
      - 8181:8181

  kavita:
    restart: unless-stopped
    image: kizaing/kavita:latest
    container_name: kavita
    volumes:
      - /home/ad/other/ebooks/comics:/comics
      - /home/ad/other/ebooks/books:/books
      - /home/ad/docker/kavita:/kavita/config
    environment:
      - TZ=America/New_York
    ports:
      - "5000:5000"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - /home/ad/docker/qbittorrent:/config
      - /home/ad/media/downloads:/downloads
      - /home/ad/media/movies:/movies
      - /home/ad/media/tvshows:/tvshows
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
