services:
  techservatory:
    restart: unless-stopped
    container_name: techservatory
    image: nginx:mainline-alpine-slim
    volumes:
      - /home/ad/techservatory/dist/:/usr/share/nginx/html/
    ports:
      - 8880:80

  tunnel:
    restart: unless-stopped
    container_name: tunnel
    image: cloudflare/cloudflared:latest
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=
